[quiz]
source = "2026小亮补充题"
tags = [ "2026" ]
extractedYear = "2026"
withExp = true


[exam_paper]
name = "2026小亮补充题"
subject = "综合"
year = "2026"


[processing]
default_chunks = 1
retry_failed = false
check_failed = false


[concurrency]
quiz_parser_limit = 15
batch_processing_limit = 5
batch_delay_ms = 500
retry_concurrency_limit = 3
max_retries = 3
retry_base_delay_ms = 1_000
